### ISSUE TITLE
Replace Envoy with YARP

### ISSUE THREAD

**Issue by mgnoonan** [dotnet-architecture/eShopOnDapr#61]
I know the initial goal of the project was to port eShopOnContainers to add Dapr features, just wondering if there has been any discussion with replacing Envoy with the [YARP project](https://github.com/microsoft/reverse-proxy/issues) now that it has gone RC1?

**Comment by amolenk** [comment]
Yes, the main focus is still on the use of the Dapr building blocks. Haven't looked at YARP in detail yet, there are currently no plans for replacing Envoy. One thing I noticed is that it ships as a NuGet package. That'd mean we must add another .NET service to the solution instead of using the Envoy container image.
Any thoughts on the benefits of using YARP over Envoy for eShopOnDapr?

**Comment by mgnoonan** [comment]
Envoy is probably more mature and has performance benefits, so I don't have anything specific in mind that YARP would bring to the table. It's more about keeping it within the C# family of products. I agree, it doesn't ship as a stand alone container, but one more container build didn't seem like that much of a burden.

If you want to stick with Envoy, that's fine. I was just floating the idea. 😄

**Comment by danmoseley** [comment]
cc @tratcher in case he wants to add anything.
